USE [PatchWindows]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tblTasks](
	[taskName] [varchar](50) NOT NULL,
	[taskDescription] [varchar](50) NOT NULL,
	[taskNextRunTime] [datetime] NOT NULL,
 CONSTRAINT [PK_tblTasks] PRIMARY KEY CLUSTERED 
(
	[taskName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO